[build]
    command = "pnpm run build"
    publish = ".next"
    framework = "#static"
[build.environment]
    NPM_FLAGS="--version"
[[plugins]]
    package = "@netlify/plugin-nextjs"
[[plugins]]
    package = "./plugins/pnpm-preinstaller"