[build]
    command = "pnpm run build"
    publish = ".next"
    framework = "#static"
[build.environment]
    NPM_FLAGS="--version"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[plugins]]
    package = "@netlify/plugin-nextjs"
[[plugins]]
    package = "./plugins/pnpm-preinstaller"