[build]
    command = "npm run build"
    publish = "out"
[build.environment]
    NPM_FLAGS="--version"
[[plugins]]
    package = "@netlify/plugin-nextjs"
[[plugins]]
    package = "./plugins/pnpm-preinstaller"